import { ShieldCheck, AlertTriangle, FileText } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export default function Disclaimer() {
  return (
    <div className="p-6 max-w-3xl space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          <h1 className="text-xl font-semibold">Legal Disclaimer & Risk Disclosure</h1>
        </div>
        <p className="text-sm text-muted-foreground mt-1">
          Please read this disclosure carefully before using GateKeeper AI.
        </p>
      </div>

      {/* Warning banner */}
      <div className="flex items-start gap-3 p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/30">
        <AlertTriangle className="w-5 h-5 text-yellow-400 mt-0.5 flex-shrink-0" />
        <div>
          <p className="text-sm font-semibold text-yellow-400 mb-1">Trading involves significant risk of loss</p>
          <p className="text-xs text-muted-foreground leading-relaxed">
            You can lose some or all of your invested capital. Past performance of any trading signal, model,
            or strategy is not indicative of future results. The information provided by GateKeeper AI does not
            constitute financial advice, investment advice, trading advice, or any other type of advice.
          </p>
        </div>
      </div>

      <Card>
        <CardContent className="pt-5 space-y-5 text-xs text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">1. Not Financial Advice</h2>
            <p>
              GateKeeper AI is a paper-trading evaluation and decision-support tool designed for educational and research purposes.
              All content, signals, recommendations, scores, and outputs generated by this platform are provided for
              informational purposes only and do not constitute financial, investment, trading, legal, tax, or any other
              professional advice. Nothing on this platform should be construed as a solicitation or offer to buy or sell
              any security or financial instrument.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">2. No Registered Advisory Relationship</h2>
            <p>
              GateKeeper AI is not a registered investment advisor, broker-dealer, or financial planner under any applicable law or regulation,
              including but not limited to the Investment Advisers Act of 1940, the Securities Exchange Act of 1934, or any applicable
              state or foreign securities laws. Use of this platform does not create any advisory, fiduciary, or client relationship.
              You should consult a licensed financial professional before making any investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">3. Paper Trading Only</h2>
            <p>
              During the 90-day evaluation period, GateKeeper AI operates exclusively with Alpaca paper trading accounts —
              simulated accounts that use real market data but do not involve real money. Paper trading results may differ
              materially from live trading results due to execution differences, market impact, slippage, and other factors.
              A system's performance in a paper environment is not a guarantee of equivalent performance in a live environment.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">4. Risk of Loss</h2>
            <p>
              Securities trading involves a substantial risk of loss. Leveraged instruments, options, and short selling carry
              additional risk beyond principal investment. You should carefully consider your investment objectives, risk tolerance,
              and financial situation before making any trading decisions. Do not invest money you cannot afford to lose.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">5. AI Signal Limitations</h2>
            <p>
              GateKeeper AI uses algorithmic models, technical indicators, sentiment analysis, and heuristic rules to generate
              trading signals. These models have inherent limitations and may produce incorrect, incomplete, or misleading outputs.
              AI-generated signals are based on historical patterns and market data that may not predict future market behavior.
              Market conditions, economic events, geopolitical developments, and other factors can cause actual outcomes to deviate
              significantly from model predictions.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">6. No Warranty</h2>
            <p>
              This platform is provided "as is" without warranty of any kind, express or implied. We do not warrant that the platform
              will be error-free, uninterrupted, or free of harmful components. We are not liable for any damages arising from
              reliance on the information provided, system downtime, technical errors, or the actions of third-party services
              including Alpaca Markets or data providers.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">7. Third-Party Services</h2>
            <p>
              GateKeeper AI integrates with Alpaca Markets for order execution and market data, and MarketAux for news sentiment.
              These services are provided by third parties subject to their own terms of service and risk disclosures. We are not
              responsible for the accuracy, reliability, or availability of third-party data or services.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">8. Forward-Looking Statements</h2>
            <p>
              Any statements about potential outcomes, target prices, expected returns, or future performance are forward-looking
              and speculative. Actual results may differ materially. These statements are not guarantees of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold text-foreground mb-2">9. Jurisdiction</h2>
            <p>
              This disclaimer is governed by the laws of the United States. Use of this platform in jurisdictions where algorithmic
              trading tools or financial software are restricted or prohibited is at the user's own risk and discretion.
              Users are responsible for ensuring compliance with all applicable local laws and regulations.
            </p>
          </section>

          <div className="pt-2 border-t border-border text-muted-foreground/70">
            <p>Last updated: April 2026. This disclaimer is subject to change without notice.</p>
          </div>
        </CardContent>
      </Card>

      {/* Acknowledgment block */}
      <div className="flex items-start gap-3 p-4 rounded-lg bg-primary/5 border border-primary/20">
        <ShieldCheck className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" />
        <div>
          <p className="text-sm font-semibold text-foreground mb-1">By using GateKeeper AI, you acknowledge:</p>
          <ul className="text-xs text-muted-foreground space-y-1 list-none">
            <li>✓ You understand this is an educational and evaluation tool, not financial advice</li>
            <li>✓ You are trading in a paper (simulated) environment during the 90-day evaluation</li>
            <li>✓ You accept full responsibility for any real-world trading decisions you make</li>
            <li>✓ You have read and understood this Risk Disclosure in full</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
